const HAS_SESSION = 'HAS_SESSION';
const REGISTRATION_DATA = 'REGISTRATION_DATA';
const USER_PROFILE = 'USER_PROFILE';
const LOGOUT = 'LOGOUT';
const USER_ASSET = 'USER_ASSET';
const ASSET_LIST = 'ASSET_LIST';
const SELECTED_INDEX = 'SELECTED_INDEX';
const ASSET_NAME = 'ASSET_NAME';
const KEYWORD = 'KEYWORD';
const IMAGES_COUNT = 'IMAGES_COUNT';
const SKETCHES_COUNT = 'SKETCHES_COUNT';
const VIDEOS_COUNT = 'VIDEOS_COUNT';
const DOCUMENTS_COUNT = 'DOCUMENTS_COUNT';
const LINKS_COUNT = 'LINKS_COUNT';
const NOTES_COUNT = 'NOTES_COUNT';
const AUDIOS_COUNT = 'AUDIOS_COUNT';
const TOTAL = 'TOTAL';
const SUBSCRIPTION = 'SUBSCRIPTION'
const SUBSCRIBED_PACKAGE = 'SUBSCRIBED_PACKAGE'
const RECEIPT = 'RECEIPT'
const STORAGE = 'STORAGE'






export {
  //
  HAS_SESSION,
  REGISTRATION_DATA,
  LOGOUT,
  //
  USER_PROFILE,
  USER_ASSET,
  ASSET_LIST,
  SELECTED_INDEX,
  ASSET_NAME,
  KEYWORD,
  IMAGES_COUNT,
  SKETCHES_COUNT,
  VIDEOS_COUNT,
  DOCUMENTS_COUNT,
  LINKS_COUNT,
  NOTES_COUNT,
  AUDIOS_COUNT,
  TOTAL,
  SUBSCRIPTION,
  SUBSCRIBED_PACKAGE,
  RECEIPT,
  STORAGE
};
